title: SuperKit
description: SuperDB documentation, tutorials, and recipes
theme: just-the-docs
url: "https://chrismo.github.io"
baseurl: "/superkit"
permalink: pretty
color_scheme: dark
exclude: ["src", "node_modules", "dist", "tmp", "test", "bin", "README.md"]
