#!/usr/bin/env bash

set -euo pipefail

function _script_dir() {
  dirname "${BASH_SOURCE[0]}"
}

function _super() {
  echo "building super"
  pushd ../super
  make clean build install
  cp ./dist/super /usr/local/bin
  ls -la /usr/local/bin/super

  super --version

  # returns (separated by hyphens):
  # - latest tag (e.g. v1.18.0)
  # - number of commits since the tag
  # - abbreviated commit object prefixed with `g` for git
  #
  # The last hash SHOULD match the last commit hash (plus a `g` prefix)
  echo "Version: $(git describe --tags --dirty --always)"

  popd
}

function superkit() {
  local -r dst_dir="$(_script_dir)"/tmp/

  [ -d "$dst_dir" ] && rm -r "$dst_dir"

  mkdir "$dst_dir"
  mkdir "$dst_dir"/bin
  mkdir "$dst_dir"/lib

  cat "$(_script_dir)"/src/*.spq >"$dst_dir"/lib/superkit.spq

  cp -v "$(_script_dir)"/bin/sk* "$dst_dir"/bin/

  mkdir "$dst_dir"/lib/doc
  cp -v "$(_script_dir)"/doc/* "$dst_dir"/lib/doc/

  # install gtar with `brew install gnu-tar` on macOS
  gtar -czf "$(_script_dir)"/dist/superkit.tar.gz -C "$dst_dir" .
}

function test() {
  "$(_script_dir)"/test.sh
}

function skgrok() {
  fn="../super/pkg/grok/base.go"

  super -z -i line -c "
    grep('h.Must')
    | grok('.*h.Must\\\\(\"%{USERNAME:pattern_name}.*?\`%{GREEDYDATA:regex}\`', this)" $fn \
    >./bin/skgrok.jsup
}

function _parse_spqs() {
  local record name spq_fn

  for fn in ./src/*spq; do
    while IFS=$'\n' read -r record; do
      name=$(echo "$record" | zq -f text 'yield this.name' -)
      spq_fn=$(echo "$record" | zq -f text 'yield this.filename' -)

      super -z -I ./src/skops.spq -I "$spq_fn" -c "$name()"
    done < <(
      super -i line -z -I ./src/skops.spq \
        -c "skdoc_parse_file_contents(this) | filename:='$fn'" "$fn"
    )
  done >"$(_script_dir)"/bin/skops.jsup
}

function _parse_super_mds() {
  echo "--$(date)--"
  for fn in "$(_script_dir)"/../super/docs/language/**/*md; do
    if ! grep -q '```mdtest-spq' "$fn"; then
      echo >&2 "skipping $fn"
      continue
    fi

    echo >&2 "$fn"
    super -i line -z -c '
      op parse_spq_test(test_record): (
        test_record.i:=f"[{join(test_record.inputs, ",")}] | over this | {test_record.spq[0]}",
        test_record.o:=join(test_record.outputs, " ↵ ")
      )

      op process_chunk(chunk): (
        split(chunk, " ↵ ")
        | over this | where len(this) > 0 | collect(this)
      )

      op parse_spq_tests(line): (
        grok(".*?# spq%{DATA:spq}# input%{DATA:inputs}# expected output%{GREEDYDATA:outputs}", line)
        | spq:=(over [this] | process_chunk(this.spq)),
          inputs:=(over [this] | process_chunk(this.inputs)),
          outputs:=(over [this] | process_chunk(this.outputs))
        | parse_spq_test(this)
        | cut i,o
        | collect(this)
        | {examples: this}
      )

      collect(this)                      // collect all lines to get the entire file
      | join(this, " ↵ ")                // make it all one string
      | split(this, "```mdtest-spq")[1:] // drop the 0th item before the first occurrence
      | over this
      | grok("%{DATA:data}```", this)
      | parse_spq_tests(this.data)
      ' "$fn" |
      super -z -c "{name:'$(basename "$fn" ".md")', type:'op', ...this}" -

  done >>"$(_script_dir)"/bin/skops.jsup

}

function skops() {
  _parse_spqs
  _parse_super_mds
}

function default() {
  test
  skgrok
  skops
  superkit
}

function _usage() {
  grep -E '^function' "${BASH_SOURCE[0]}" | sort
}

function usage() {
  _usage | less -FX
}

if [ $# -eq 0 ]; then
  default
else
  while getopts "ho:" opt; do
    case $opt in
    h)
      usage
      exit 0
      ;;
    o) opt="$OPTARG" ;;
    \?) # ignore invalid options
      ;;
    esac
  done

  # Remove options processed by getopts, so the remaining args can be handled
  # positionally.
  shift $((OPTIND - 1))

  "$@"
fi
